### ISSUE TITLE
Initial start

### ISSUE THREAD

**Issue by jochenkirstaetter** [RickStrahl/WestWindWebSurge#24]
Hi Rick,
I got an error on first initial start of WebSurge - installed via chocolatey and double-clicked EXE in Explorer directly. Following is the content of WebSurgeErrors.log:

27/07/2015 15:53:30 - Object reference not set to an instance of an object.
---
WebSurge
   at WebSurge.StressTestForm.AddRecentFiles(Object sender, CancelEventArgs e)
   at WebSurge.StressTestForm.StressTestForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jochenkirstaetter** [comment]
Related to this:

27/07/2015 16:03:26 - Object reference not set to an instance of an object.
---
WebSurge
   at WebSurge.StressTestForm.AddRecentFiles(Object sender, CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDown(Boolean mousePush)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jochenkirstaetter** [comment]
And any further start is okay without those errors. 
So, it's only related to the very first start of the application I guess.

Cheers, JoKi

**Comment by RickStrahl** [comment]
Thanks @jochenkirstaetter. Fixed.

Issue was a regression as I went back to manually tracking the recentlist in the configuration file rather than using the Windows Recentlist which proved to be very inconsistent. Null list when the configuration doesn't exist was causing the problem.

I've updated the download so shouldn't see this any longer.
